export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_GET_USER_INFO = 'AUTH_GET_USER_INFO'
export const AUTH_UPDATE_USER_INFO = 'AUTH_UPDATE_USER_INFO'
export const GET_INSTITUTE_LIST = 'GET_INSTITUTE_LIST'
